### ISSUE TITLE
UI: Screen to list available schemas

### ISSUE THREAD

**Issue by remiges-sachin** [remiges-tech/rigel-ui#1]
Develop the screen that lists all available schemas in the Rigel.

The task will involve:

- Retrieving all available schemas from the Rigel system.
- Displaying the schemas in a list format on the screen. It will show app and module name, latest version and description. 
- Add an icon in the schema entry to view the list of all the configurations associated with it.
- Add another icon to add a new configuration associated with this schema.
- Implementing functionality to allow users to view details of a schema from the list.
- Implementing error handling to manage scenarios where no schemas are available.

The web service specifications are at [schema-get web service](https://github.com/remiges-tech/rigel/wiki/Web-services#schema-get)

**Comment by remiges-sufiyaan** [comment]
Developed the screen that lists all available schema's in the Rigel.

**Comment by remiges-sufiyaan** [comment]
Schema list UI completed
