### ISSUE TITLE
UI: Screen to display schema details

### ISSUE THREAD

**Issue by remiges-sachin** [remiges-tech/rigel-ui#2]
Develop the screen that displays a Rigel schema details. 

The task will involve:

- Fetching detailed information about the selected schema from [schema-get web service(https://github.com/remiges-tech/rigel/wiki/Web-services#schema-get).
- Displaying the schema details in a user-friendly format on the screen.
- Implementing functionality to allow users to edit the schema details, if necessary.
- Implementing error handling to manage scenarios where the selected schema does not exist or cannot be fetched.

It will also have a button or a link that says "View Configurations". Clicking on this will lead to the Configuration List Screen.

**Comment by remiges-sufiyaan** [comment]
Developed screen to display schema details inside the form,
applied complete validation throughout the form.
